name: Build & Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout code
        uses: actions/checkout@v4

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build & push Docker image using Git commit SHA
      - name: Build and push Docker image
        run: |
          IMAGE_TAG=${GITHUB_SHA::7}
          echo "Using image tag: $IMAGE_TAG"
          echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}"
          echo "IMAGE_TAG=$IMAGE_TAG"

          docker build -t ${{ secrets.DOCKER_USERNAME }}/simple-api:$IMAGE_TAG .
          docker push ${{ secrets.DOCKER_USERNAME }}/simple-api:$IMAGE_TAG

      # Setup SSH to EC2
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts

      # Deploy on EC2 using the SAME commit SHA
      - name: Deploy on EC2
        run: |
          IMAGE_TAG=${GITHUB_SHA::7}
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/simple-api:$IMAGE_TAG

          ssh ubuntu@${{ secrets.EC2_PUBLIC_IP }} << EOF
            set -e

            echo "Deploying image tag: $IMAGE_TAG"

            docker pull $IMAGE_NAME

            docker stop simple-api || true
            docker rm simple-api || true

            docker run -d \
              --name simple-api-prod \
              -p 3000:3000 \
              --restart unless-stopped \
              $IMAGE_NAME
          EOF
